name: Secure Deploy with Docker Compose

on:
  push:
    branches:
      - main # Executa o deploy em push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar acesso SSH à VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Transferir arquivos do repositório para a VPS, excluindo o .env
      - name: Transfer Files to VPS
        run: |
          rsync -avz --exclude '.git' --exclude '.env' ./ root@177.153.51.58:/home/grocha/applications/ \
          --rsync-path="sudo rsync"

      # 4. Atualizar os containers com docker-compose
      - name: Deploy with Docker Compose
        run: |
          ssh user@your-vps-ip << 'EOF'
          cd /path/to/your/project
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF
