name: Secure Deploy with Docker Compose

on:
  push:
    branches:
      - main # Executa o deploy em push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar acesso SSH à VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Adicionar a chave pública da VPS ao known_hosts
      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 177.153.51.58 >> ~/.ssh/known_hosts

      # 4. Transferir arquivos do repositório para a VPS, excluindo o .env
      - name: Transfer Files to VPS
        run: |
          rsync -avz --exclude '.git' --exclude '.env' ./ root@177.153.51.58:/home/grocha/applications/ \
          --rsync-path="sudo rsync"

      # 5. Atualizar os containers com docker-compose
      - name: Deploy with Docker Compose
        run: |
          ssh root@177.153.51.58 << 'EOF'
          cd /home/grocha/applications
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF
