name: Secure Deploy with Docker Compose

on:
  push:
    branches:
      - main  # Ou a branch que você quer monitorar
  workflow_dispatch:  # Permite disparar o workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o acesso SSH à VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Adicionar o host ao known_hosts
      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 177.153.51.58 >> ~/.ssh/known_hosts

      # 4. Transferir os arquivos para a VPS
      - name: Transfer Files to VPS
        run: |
          rsync -e "ssh -i ~/.ssh/id_rsa" -avz --exclude '.git' --exclude '.env' ./ root@177.153.51.58:/home/grocha/applications/

      # 5. Atualizar os containers com docker-compose
      - name: Deploy with Docker Compose
        run: |
          ssh root@177.153.51.58 << 'EOF'
          cd /home/grocha/applications
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF
